# Generated by Django 4.1.4 on 2023-01-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('volume_number', models.SmallIntegerField()),
                ('genre', models.CharField(blank=True, max_length=25, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('publishing_house', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=50)),
                ('volume_count', models.SmallIntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('product_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.books')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.series'),
        ),
    ]
