# Generated by Django 4.1.4 on 2023-01-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='covers'),
        ),
    ]
