# Generated by Django 4.1.4 on 2023-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ownedproducts_product'),
        ('store', '0004_alter_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='covers'),
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
