# Generated by Django 4.1.4 on 2023-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_books_cover_delete_edition_delete_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=6, null=True),
        ),
    ]
