# Generated by Django 4.1.4 on 2023-02-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_authors_first_name_remove_authors_last_name_and_more'),
        ('accounts', '0003_userauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthor',
            name='author_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.authors', unique=True),
        ),
    ]
