# Generated by Django 4.1.4 on 2023-03-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userauthor_author_ref'),
    ]

    operations = [
        migrations.RenameModel('UserAuthor', 'Profile')
    ]
