# Generated by Django 4.1.4 on 2023-01-06 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_alter_books_cover_delete_edition_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('order_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.books')),
            ],
        ),
    ]
